// Autogenerated UI can't call namespaced functions, so we have these:
function PlayPauseOnClick() {
    pega.u.d.Tracer.stopStart();
}
function clear() {
    pega.u.d.Tracer.clear();
}
function launchSettings() {
    pega.u.d.Tracer.launchSettings();
}
function launchBreakpoints() {
    pega.u.d.Tracer.launchBreakpoints();
}
function launchWatch() {
    pega.u.d.Tracer.launchWatch();
}
function launchRemoteTrace() {
    pega.u.d.Tracer.launchRemoteTrace();
}
function exportTrace() {
    pega.u.d.Tracer.exportTrace();
}